### ISSUE TITLE
Option to stage provided DOI as "other access DOI"

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-stage-dataset#18]
Since version 2.12 EASY will have the option to use an "other access DOI" instead of a DANS managed DOI. It must be marked in the EASY Metadata with eas:scheme="DOI_OTHER_ACCESS". In the user interface this DOI will then be used to refer users to the access point of the dataset.

See (in the private DANS JIRA database):
https://drivenbydata.atlassian.net/browse/EASY-935
https://drivenbydata.atlassian.net/browse/EASY-932

Create a boolean option `--stage-other-access-doi` that instructs `easy-stage-dataset` to stage the provided DOI as the "other access DOI". If the option is set to `true` it is an error:
* to provide a DANS generated DOI
* if the bag to stage contains no DOI
* if the bag to stage contains more than one DOI

**Comment by janvanmansum** [comment]
@GeorgiKhomeriki @PaulBoon @ekoi please review this issue to see if it makes sense.

**Comment by GeorgiKhomeriki** [comment]
If `--stage-other-access-doi` is set to false, do we then need to generate a DANS DOI in this tool?

**Comment by janvanmansum** [comment]
No, but we could provide it to the tool (similar to how we provide the URN). I guess that is another requirement that needs to be implemented.

**Comment by janvanmansum** [comment]
Solved by #29
