### ISSUE TITLE
Add option to stage dataset in Fedora to disk

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-stage-dataset#25]
Background
=========

Apart from using a "bag" as the source for the resulting SDO-set it should also be possible to use a dataset in Fedora as the source. This would be useful for copying datasets between EASY Fedora Repo instances. Specifically this could come in handy when trying to diagnose an error that only seems to happen with some datasets in the production environment.

Specifications
===========

Let's make this a "smart" option, in that `easy-stage-dataset` will first try to match its first argument to a directory. If that fails, it will check if the first argument has the format of a dataset PID (i.e. `easy-dataset:\d+`) and if so will try to use that dataset as a source.

Example
======

Example session that would create an SDO-set at the directory `exported_dataset_123` (assuming that the Fedora user and password are configured in `application.properties`:
         
    easy-stage-dataset easy-dataset:123 exported_dataset_123

Notes
====

Make sure that the "round-trip" always works. So, after staging a dataset from Fedora, ingest it using `easy-ingest` to see if it yields a set of digital objects in Fedora that contain the same data (and metadata) as the original dataset, taking into account that some things are bound to be different (the PID, the modified date, etc).

It may be necessary to extends `easy-ingest` with a format to support multiple datastream versions. A separate issue must be created for this.

**Comment by janvanmansum** [comment]
@GeorgiKhomeriki @jo-pol @ekoi @PaulBoon please review these specs.

**Comment by jo-pol** [comment]
Users between repositories won't match. So what to do with user-ids in the FOXML, such as the depositorId in the AMD and requesterId in permission request. The stage/ingest tools also won't copy data relating to a dataset such as the donwload history.

**Comment by jo-pol** [comment]
@GeorgiKhomeriki @janvanmansum 

The current command line requires a URN and DOI. These are not applicable for draft datasets. Don't we want to be able to copy draft datasets too?

**Comment by GeorgiKhomeriki** [comment]
I think that once we stage datasets they are in the process to be committed, so the draft state doesn't apply here.

**Comment by janvanmansum** [comment]
Well, if we are using it as a tool to copy a dataset from one EASY installation to another then @jo-pol 's question is valid. We might make the `--urn` and `--doi` options non-mandatory.

**Comment by janvanmansum** [comment]
After discussion at today's Development Team meeting we concluded that creating an `easy-export-dataset` tool that exports a dataset to BagIt format would be a more promising avenue to explorer first. (Thanks @PaulBoon, for remarking this :+1: ) @jo-pol @ekoi @vesaakerman @GeorgiKhomeriki

**Comment by janvanmansum** [comment]
Closing this issue. If the BagIt-export does not turn out to be viable, we could reopen it.
