### ISSUE TITLE
EASY-BagIt schema?

### ISSUE THREAD

**Issue by GeorgiKhomeriki** [DANS-KNAW/easy-stage-dataset#28]
It seems that the EASY-BagIt schema has been removed: http://easy.dans.knaw.nl/schemas/EASY-BagIt.html
Although it's strictly not the schema for `easy-deposit`, `easy-stage-dataset` does require the EASY-BagIt format. Perhaps we should put the schema back?

**Comment by janvanmansum** [comment]
The extra requirements for a deposit (apart from that it needs to be a BagIt bag) definitely need to be documented somewhere. However, I don't think we really need a schema for it. The documentation should probably just be part of the new "SWORD Manual".
