### ISSUE TITLE
Stage license as "additional licence" if URL in dcterms license field is recognized

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-stage-dataset#31]
Feature
======
If in the DDM-file in a `dcterms:license`-element:
* the syntax encoding scheme [URI](http://dublincore.org/documents/dcmi-terms/#terms-URI) is specified, as a `xsi:type="dcterms:URI"` attribute
* the URI is one of a configured list of URLs of open source licenses

Then the matching open source license must be staged as an additional license for the dataset

Open Questions
=============
* How to configure the list of recognized URLs and the mapping to the license file?
* Where to store the licences? (Suggestion: in `app.home/lic`)
* What to do if there is more than one `dcterms:license` element?

**Comment by janvanmansum** [comment]
@GeorgiKhomeriki @jo-pol @PaulBoon @ekoi please have a look. Do these specs make sense? Any suggestions on the open questions?

**Comment by GeorgiKhomeriki** [comment]
* "How to configure the list of recognized URLs and the mapping to the license file?"
  - Key-value pairs in the properties file? Or a dedicated JSON/CSV file?
* "Where to store the licences? (Suggestion: in app.home/lic)"
  - Sounds good. Another option is not storing them, but then we would need to download them each time.
* "What to do if there is more than one dcterms:license element?"
  - Stage multiple additional licenses? Seems to me that that isn't unreasonable.

**Comment by janvanmansum** [comment]
Partly done. The solution does not yet take into account the `xsi:type` attribute. If it is set to `dcterms:URI` the license must be loaded from the `lic` directory, if there is no `xsi:type` the contents of the `license` element must be used as the license content.

**Comment by janvanmansum** [comment]
Solved
