### ISSUE TITLE
Make submissiontimestamp, urn and doi optional

### ISSUE THREAD

**Issue by janvanmansum** [DANS-KNAW/easy-stage-dataset#36]
@DANS-KNAW/easy 
EASY-921

* submissiontimestamp must default to the current time
* if `urn` or `doi` is left out the dataset state should be set to `DRAFT`.

The defaults should be implemented in the core library, not in the command line interface.

**Comment by janvanmansum** [comment]
@jo-pol @GeorgiKhomeriki @ekoi @PaulBoon @vesaakerman please review, do these specs make sense?

**Comment by jo-pol** [comment]
@janvanmansum you can close this one
