### ISSUE TITLE
licen[c|s]e typo

### ISSUE THREAD

**Issue by jo-pol** [DANS-KNAW/easy-stage-dataset#39]
In example-bag/meatadata/dataset.xml licen[c|s]e is spelled incorrectly
MD5 should also be recalculated and everything re-zipped

**Comment by janvanmansum** [comment]
Fixed

**Comment by jo-pol** [comment]
I fixed only the typos, not the checksums.

**Comment by janvanmansum** [comment]
Well, something to keep in mind in future changes you make to bags. Always update the checksums after updating a bag. Use the Library of Congress tools, as explained [here (see step 6)](https://github.com/DANS-KNAW/easy-deposit/wiki/HOWTO---Create-an-EASY-Deposit-Bag)
